# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^(docs/|notebooks/|data/|src/secrets/|src/static/|src/templates/)
default_language_version:
    python: python3.8
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
        - "--max-line-length=120"
        - "--max-complexity=18"
        - "--select=B,C,E,F,W,T4,B9"
        - "--ignore=E203,E266,E501,W503,F403,F401,E402"

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    - id: isort
      args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      # exclude: ^(docs/|notebooks/|data/|src/secrets/)
      args:
        - --line-length=120
